<?php

/**
 * DirectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DirectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Director');
    }
}